import {
  COriginal,
  JavascriptOriginal,
  TypescriptOriginal,
  ReactOriginal,
  NodejsOriginal,
  ExpressOriginal,
  Html5Original,
  Css3Original,
  TailwindcssOriginal,
  BootstrapOriginal,
  MaterialuiOriginal,
  MysqlOriginal,
  GitOriginal,
  AntdesignOriginal,
  GithubOriginal,
  PostmanOriginal,
  VscodeOriginal,
  ReduxOriginal,
  MongodbOriginal,
  FilezillaOriginal,
  PhpOriginal,
  WordpressOriginal,
  ViteOriginal,
} from "devicons-react";

export const MySkills = [
  {
    title: "Programming Languages",
    skills: [
      { name: "C", icon: COriginal },
      { name: "JavaScript", icon: JavascriptOriginal },
      { name: "TypeScript", icon: TypescriptOriginal },
      { name: "PHP", icon: PhpOriginal },
    ],
    index: 1,
  },
  {
    title: "Frontend Development",
    skills: [
      { name: "React.js", icon: ReactOriginal },
      { name: "HTML", icon: Html5Original },
      { name: "CSS", icon: Css3Original },
      { name: "Tailwind CSS", icon: TailwindcssOriginal },
      { name: "Bootstrap", icon: BootstrapOriginal },
      { name: "Material UI", icon: MaterialuiOriginal },
      { name: "Ant Design", icon: AntdesignOriginal },
      { name: "Redux", icon: ReduxOriginal },
      { name: "Vite", icon: ViteOriginal },
    ],
    index: 2,
  },
  {
    title: "Backend Development",
    skills: [
      { name: "Node.js", icon: NodejsOriginal },
      { name: "Express.js", icon: ExpressOriginal },
      { name: "WordPress", icon: WordpressOriginal },
    ],
    index: 3,
  },
  {
    title: "Databases",
    skills: [
      { name: "MySQL", icon: MysqlOriginal },
      { name: "MongoDB", icon: MongodbOriginal },
    ],
    index: 4,
  },
  {
    title: "Tools",
    skills: [
      { name: "Git", icon: GitOriginal },
      { name: "GitHub", icon: GithubOriginal },
      { name: "Visual Studio Code", icon: VscodeOriginal },
      { name: "Postman", icon: PostmanOriginal },
      { name: "FileZilla", icon: FilezillaOriginal },
    ],
    index: 5,
  },
];
